/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalogo/musculos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Muscles */
        get: operations["list_muscles_api_catalogo_musculos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogo/ejercicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_catalogo_ejercicios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogo/ejercicios/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_catalogo_ejercicios__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogo/reglas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_catalogo_reglas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rutinas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Routines */
        get: operations["list_routines_api_rutinas_get"];
        put?: never;
        /** Create Routine */
        post: operations["create_routine_api_rutinas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rutinas/{routine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routine */
        get: operations["get_routine_api_rutinas__routine_id__get"];
        /**
         * Update Routine
         * @description Editar **crea una versión nueva**; la anterior queda intacta (regla R1).
         */
        put: operations["update_routine_api_rutinas__routine_id__put"];
        post?: never;
        /**
         * Archive Routine
         * @description Archiva, no borra: el historial referencia sus versiones.
         */
        delete: operations["archive_routine_api_rutinas__routine_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/semana": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Week */
        get: operations["get_week_api_semana_get"];
        /**
         * Set Week
         * @description Fija la semana desde una fecha. No reescribe el pasado (regla R3).
         */
        put: operations["set_week_api_semana_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/excepciones/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Exception
         * @description Un día excusado no es un incumplimiento (regla R4).
         */
        put: operations["set_exception_api_excepciones__day__put"];
        post?: never;
        /** Clear Exception */
        delete: operations["clear_exception_api_excepciones__day__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hoy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_api_hoy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dias/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day */
        get: operations["get_day_api_dias__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pendientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending
         * @description Días programados y sin registrar, resolubles de un toque.
         */
        get: operations["pending_api_pendientes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_api_calendario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendario/{year}/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar Month */
        get: operations["calendar_month_api_calendario__year___month__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones/como-planificado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log As Planned
         * @description «Hice esta rutina»: copia el plan vigente **ese día** y lo da por hecho.
         */
        post: operations["log_as_planned_api_sesiones_como_planificado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sesiones_get"];
        put?: never;
        /**
         * Log Session
         * @description Registro libre: entrenamiento extra o con desviaciones respecto al plan.
         */
        post: operations["log_session_api_sesiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones/no-realizado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip Day
         * @description Declarar que un día no se entrenó: información, no ausencia de ella.
         */
        post: operations["skip_day_api_sesiones_no_realizado_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sesiones/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sesiones__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sesiones__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rutinas/{routine_id}/progresion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evaluate Routine
         * @description Veredicto para cada ejercicio, con su motivo aunque no se pueda progresar.
         */
        get: operations["evaluate_routine_api_rutinas__routine_id__progresion_get"];
        put?: never;
        /**
         * Apply Progression
         * @description Aplica las progresiones elegidas: una versión nueva y un evento por ejercicio.
         *
         *     Se recalcula antes de escribir. Si algo dejó de ser seguro entre la
         *     pantalla y el botón, responde 409 con el motivo en vez de aplicarlo.
         */
        post: operations["apply_progression_api_rutinas__routine_id__progresion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progresion/listas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Rutinas con algo que ofrecer. Lo que avisa en «Hoy».
         */
        get: operations["readiness_api_progresion_listas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progresiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_progresiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progresiones/{event_id}/deshacer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Undo Progression
         * @description Deshacer es avanzar: crea la versión que restaura el plan anterior.
         */
        post: operations["undo_progression_api_progresiones__event_id__deshacer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ajustes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings All */
        get: operations["get_settings_all_api_ajustes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ajustes/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Setting */
        put: operations["set_setting_api_ajustes__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bodyweight History */
        get: operations["bodyweight_history_api_peso_get"];
        /** Set Bodyweight */
        put: operations["set_bodyweight_api_peso_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/peso/actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Bodyweight
         * @description ``null`` si no hay ningún registro.
         *
         *     Las métricas que dependen del peso corporal deben poder decir que no son
         *     calculables, en lugar de suponer un valor.
         */
        get: operations["current_bodyweight_api_peso_actual_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Volcado completo y autocontenido.
         *
         *     Segundo destinatario: el agente de IA (ADR-0004), que puede analizarlo sin
         *     depender del proceso vivo. El texto libre que contiene es dato, no orden.
         */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backup */
        post: operations["backup_api_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BodyweightIn */
        BodyweightIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** BodyweightOut */
        BodyweightOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** CalendarOut */
        CalendarOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Days */
            days: components["schemas"]["DayStateOut"][];
            /** Adherence */
            adherence?: number | null;
        };
        /** DayOut */
        DayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            state: components["schemas"]["DayState"];
            /** Reason */
            reason: string;
            /** Can Log */
            can_log: boolean;
            planned?: components["schemas"]["RoutineOut"] | null;
            session?: components["schemas"]["SessionOut"] | null;
            /** Exception Reason */
            exception_reason?: string | null;
        };
        /**
         * DayState
         * @description Estado de cumplimiento de un día del calendario.
         *
         *     PENDING es la razón de ser de este enum: distingue "aún no lo he
         *     registrado" de "no lo hice". Sin él, abrir la app el domingo pintaría de
         *     rojo toda la semana.
         * @enum {string}
         */
        DayState: "rest" | "done" | "partial" | "pending" | "missed" | "extra" | "excused";
        /** DayStateOut */
        DayStateOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            state: components["schemas"]["DayState"];
            /** Reason */
            reason: string;
            /** Routine Name */
            routine_name?: string | null;
            /** Routine Id */
            routine_id?: number | null;
            /** Session Id */
            session_id?: number | null;
        };
        /** ExceptionIn */
        ExceptionIn: {
            /** Reason */
            reason: string;
            /** Routine Id */
            routine_id?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Modality */
            modality: string;
            /** Load Type */
            load_type: string;
            /** Load Factor */
            load_factor: number;
            /** Is Unilateral */
            is_unilateral: boolean;
            /** Equipment */
            equipment?: string | null;
            /** Default Rule Slug */
            default_rule_slug?: string | null;
            /** Next Variant Slug */
            next_variant_slug?: string | null;
            /** Default Rest Seconds */
            default_rest_seconds: number;
            /**
             * Muscles
             * @default []
             */
            muscles: components["schemas"]["MuscleLinkOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LogAsPlannedIn
         * @description «Hice esta rutina»: el registro de un toque.
         */
        LogAsPlannedIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** @default completed */
            status: components["schemas"]["SessionStatus"];
            /** Perceived Effort */
            perceived_effort?: number | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** LogSessionIn */
        LogSessionIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Exercises */
            exercises: components["schemas"]["PerformedExerciseIn"][];
            /** @default completed */
            status: components["schemas"]["SessionStatus"];
            /** Routine Id */
            routine_id?: number | null;
            /** Perceived Effort */
            perceived_effort?: number | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** MuscleLinkOut */
        MuscleLinkOut: {
            /** Muscle Slug */
            muscle_slug: string;
            /** Role */
            role: string;
        };
        /** MuscleOut */
        MuscleOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Body View */
            body_view: string;
            /** Svg Key */
            svg_key: string;
        };
        /** PendingDayOut */
        PendingDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Routine Id */
            routine_id: number;
            /** Routine Name */
            routine_name: string;
            /** Days Left */
            days_left: number;
        };
        /** PerformedExerciseIn */
        PerformedExerciseIn: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets: components["schemas"]["PerformedSetIn"][];
        };
        /** PerformedExerciseOut */
        PerformedExerciseOut: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Position */
            position: number;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets: components["schemas"]["PerformedSetOut"][];
        };
        /** PerformedSetIn */
        PerformedSetIn: {
            /** Set No */
            set_no: number;
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Time S */
            time_s?: number | null;
            /** Rir */
            rir?: number | null;
            /**
             * Completed
             * @default true
             */
            completed: boolean;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
        };
        /** PerformedSetOut */
        PerformedSetOut: {
            /** Set No */
            set_no: number;
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Time S */
            time_s?: number | null;
            /** Rir */
            rir?: number | null;
            /**
             * Completed
             * @default true
             */
            completed: boolean;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
        };
        /** PlannedExerciseIn */
        PlannedExerciseIn: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Rule Slug */
            rule_slug?: string | null;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets?: components["schemas"]["PlannedSetIn"][] | null;
            spec?: components["schemas"]["SetSpec"] | null;
        };
        /** PlannedExerciseOut */
        PlannedExerciseOut: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Position */
            position: number;
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Rule Slug */
            rule_slug?: string | null;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets: components["schemas"]["PlannedSetOut"][];
        };
        /** PlannedSetIn */
        PlannedSetIn: {
            /** Set No */
            set_no: number;
            /** Target Reps */
            target_reps?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Target Weight Kg */
            target_weight_kg?: number | null;
            /** Target Time S */
            target_time_s?: number | null;
            /** Target Rir */
            target_rir?: number | null;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
        };
        /** PlannedSetOut */
        PlannedSetOut: {
            /** Set No */
            set_no: number;
            /** Target Reps */
            target_reps?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Target Weight Kg */
            target_weight_kg?: number | null;
            /** Target Time S */
            target_time_s?: number | null;
            /** Target Rir */
            target_rir?: number | null;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
        };
        /** ProgressionAppliedOut */
        ProgressionAppliedOut: {
            routine: components["schemas"]["RoutineOut"];
            /** Events */
            events: components["schemas"]["ProgressionEventOut"][];
        };
        /** ProgressionApplyIn */
        ProgressionApplyIn: {
            /** Exercises */
            exercises: string[];
            /** Note */
            note?: string | null;
        };
        /** ProgressionEventOut */
        ProgressionEventOut: {
            /** Id */
            id: number;
            /** Exercise Slug */
            exercise_slug: string;
            /** Exercise Name */
            exercise_name: string;
            /** Routine Id */
            routine_id: number;
            /** Routine Name */
            routine_name: string;
            /** Rule Slug */
            rule_slug: string;
            /** Rationale */
            rationale: string;
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** Actor */
            actor: string;
            /** Before Summary */
            before_summary: string;
            /** After Summary */
            after_summary: string;
            /** Before Exercise Slug */
            before_exercise_slug: string;
            /** After Exercise Slug */
            after_exercise_slug: string;
            /**
             * Reverted
             * @default false
             */
            reverted: boolean;
            /**
             * Is Reversal
             * @default false
             */
            is_reversal: boolean;
            /** From Version No */
            from_version_no?: number | null;
            /** To Version No */
            to_version_no?: number | null;
        };
        /**
         * ProgressionItemOut
         * @description Veredicto para un ejercicio.
         *
         *     ``reason`` viaja siempre, también en ``undetermined``: un cliente que solo
         *     pintara los ``ready`` estaría ocultando justo lo que hay que decidir.
         */
        ProgressionItemOut: {
            /** Exercise Slug */
            exercise_slug: string;
            /** Exercise Name */
            exercise_name: string;
            outcome: components["schemas"]["ProgressionOutcome"];
            /** Reason */
            reason: string;
            /** Current */
            current: string;
            /** Applicable */
            applicable: boolean;
            /** Rule Slug */
            rule_slug?: string | null;
            /**
             * Rule Inherited
             * @default false
             */
            rule_inherited: boolean;
            /** Proposed */
            proposed?: string | null;
            /**
             * Proposed Sets
             * @default []
             */
            proposed_sets: components["schemas"]["PlannedSetOut"][];
            /** Next Exercise Slug */
            next_exercise_slug?: string | null;
            /** Next Exercise Name */
            next_exercise_name?: string | null;
            /** Last Progression */
            last_progression?: string | null;
        };
        /**
         * ProgressionOutcome
         * @description Resultado de evaluar una progresión.
         *
         *     UNDETERMINED es un ciudadano de primera clase: cuando el sistema no puede
         *     determinar con seguridad cómo progresar, lo dice en vez de inventarlo.
         * @enum {string}
         */
        ProgressionOutcome: "ready" | "not_yet" | "undetermined" | "deload_suggested";
        /** RoutineIn */
        RoutineIn: {
            /** Name */
            name: string;
            /** Exercises */
            exercises: components["schemas"]["PlannedExerciseIn"][];
            /** Note */
            note?: string | null;
        };
        /** RoutineOut */
        RoutineOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Version Id */
            version_id: number;
            /** Version No */
            version_no: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Note */
            note?: string | null;
            /** Exercises */
            exercises: components["schemas"]["PlannedExerciseOut"][];
        };
        /** RoutineProgressionOut */
        RoutineProgressionOut: {
            /** Routine Id */
            routine_id: number;
            /** Routine Name */
            routine_name: string;
            /** Version No */
            version_no: number;
            /** Ready */
            ready: number;
            /** Deload */
            deload: number;
            /** Items */
            items: components["schemas"]["ProgressionItemOut"][];
        };
        /** RoutineReadinessOut */
        RoutineReadinessOut: {
            /** Routine Id */
            routine_id: number;
            /** Routine Name */
            routine_name: string;
            /** Ready */
            ready: number;
            /** Deload */
            deload: number;
        };
        /** RoutineSummaryOut */
        RoutineSummaryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Version No */
            version_no: number;
            /** Exercise Count */
            exercise_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RoutineUpdate */
        RoutineUpdate: {
            /** Name */
            name?: string | null;
            /** Exercises */
            exercises: components["schemas"]["PlannedExerciseIn"][];
            /** Note */
            note?: string | null;
        };
        /** RuleOut */
        RuleOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
        };
        /**
         * SessionOrigin
         * @enum {string}
         */
        SessionOrigin: "planificada" | "adhoc";
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            status: components["schemas"]["SessionStatus"];
            origin: components["schemas"]["SessionOrigin"];
            /** Routine Id */
            routine_id?: number | null;
            /** Routine Name */
            routine_name?: string | null;
            /** Routine Version No */
            routine_version_no?: number | null;
            /** Perceived Effort */
            perceived_effort?: number | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Notes */
            notes?: string | null;
            /** Logged At */
            logged_at?: string | null;
            /**
             * Is Retroactive
             * @default false
             */
            is_retroactive: boolean;
            /** Exercises */
            exercises: components["schemas"]["PerformedExerciseOut"][];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "completed" | "partial" | "skipped";
        /**
         * SetSpec
         * @description Prescripción compacta: la UI dice "3x15" y el backend genera las filas.
         */
        SetSpec: {
            /** Count */
            count: number;
            /** Reps */
            reps?: number | null;
            /** Reps Max */
            reps_max?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Time S */
            time_s?: number | null;
            /** Rir */
            rir?: number | null;
            /**
             * Warmup
             * @default 0
             */
            warmup: number;
        };
        /** SettingIn */
        SettingIn: {
            /** Value */
            value: unknown;
        };
        /** SkipDayIn */
        SkipDayIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeekIn */
        WeekIn: {
            /** Days */
            days: {
                [key: string]: number | null;
            };
            /** Effective From */
            effective_from?: string | null;
        };
        /** WeekOut */
        WeekOut: {
            /**
             * Effective On
             * Format: date
             */
            effective_on: string;
            /** Days */
            days: {
                [key: string]: number | null;
            };
            /** Names */
            names: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_muscles_api_catalogo_musculos_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuscleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_catalogo_ejercicios_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_catalogo_ejercicios__slug__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_catalogo_reglas_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routines_api_rutinas_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_routine_api_rutinas_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routine_api_rutinas__routine_id__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routine_api_rutinas__routine_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_routine_api_rutinas__routine_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_week_api_semana_get: {
        parameters: {
            query?: {
                at?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_week_api_semana_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeekIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_exception_api_excepciones__day__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExceptionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_exception_api_excepciones__day__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_hoy_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_api_dias__day__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_api_pendientes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_calendario_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_month_api_calendario__year___month__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_as_planned_api_sesiones_como_planificado_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogAsPlannedIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sesiones_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_session_api_sesiones_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skip_day_api_sesiones_no_realizado_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipDayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sesiones__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sesiones__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_routine_api_rutinas__routine_id__progresion_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineProgressionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_progression_api_rutinas__routine_id__progresion_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                routine_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressionApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionAppliedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readiness_api_progresion_listas_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineReadinessOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_progresiones_get: {
        parameters: {
            query?: {
                routine_id?: number | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_progression_api_progresiones__event_id__deshacer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressionAppliedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_salud_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_all_api_ajustes_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_setting_api_ajustes__key__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bodyweight_history_api_peso_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyweightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_bodyweight_api_peso_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyweightIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyweightOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_bodyweight_api_peso_actual_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyweightOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_api_backup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
